version: '3.4'
services:
  musketeers:
    build: .
    image: flemay/musketeers:latest
    command: bash
    env_file: .env
    volumes:
      - type: bind
        source: .
        target: /opt/app
    working_dir: /opt/app