version: '3.4'
services:
  my-alpine:
    build: .
    image: rw/alpine-test:latest
    command: bash
    env_file: .env
    volumes:
      - type: bind
        source: /opt/app
        target: /opt/app
    # working_dir: /opt/app